blueprint:
  name: Inovelli VZW32-SN Red Series Switch (Z-Wave JS Updated)
  description: >
    Updated for modern Z-Wave JS versions that use numeric Central Scene values.
  domain: automation

  input:
    inovelli_switch:
      name: Inovelli Red Series Switch
      selector:
        device:
          integration: zwave_js

    button_1x_up:
      name: Up - Single Tap
      default: []
      selector:
        action: {}

    button_2x_up:
      name: Up - Double Tap
      default: []
      selector:
        action: {}

    button_3x_up:
      name: Up - Triple Tap
      default: []
      selector:
        action: {}

    button_1x_down:
      name: Down - Single Tap
      default: []
      selector:
        action: {}

    button_2x_down:
      name: Down - Double Tap
      default: []
      selector:
        action: {}

    button_3x_down:
      name: Down - Triple Tap
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input inovelli_switch

variables:
  button_id: "{{ trigger.event.data.property_key_name }}"
  press_count: "{{ trigger.event.data.value | int }}"

action:
  - choose:

      # =============================
      # UP BUTTON (001)
      # =============================

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "001" and press_count == 0 }}
        sequence: !input button_1x_up

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "001" and press_count == 3 }}
        sequence: !input button_2x_up

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "001" and press_count == 4 }}
        sequence: !input button_3x_up


      # =============================
      # DOWN BUTTON (002)
      # =============================

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "002" and press_count == 0 }}
        sequence: !input button_1x_down

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "002" and press_count == 3 }}
        sequence: !input button_2x_down

      - conditions:
          - condition: template
            value_template: >
              {{ button_id == "002" and press_count == 4 }}
        sequence: !input button_3x_down
