blueprint:
  name: Inovelli VZW32-SN Red Series Switch (Z-Wave JS Numeric Central Scene)
  description: >
    Updated blueprint for Z-Wave JS numeric Central Scene values.
    Mapping verified:
      002 = Up paddle
      001 = Down paddle
      0 = Single tap
      3 = Double tap
      4 = Triple tap
  domain: automation

  input:
    inovelli_switch:
      name: Inovelli Red Series Switch
      selector:
        device:
          integration: zwave_js

    # =============================
    # UP BUTTON ACTIONS (002)
    # =============================

    button_1x_up:
      name: Up - Single Tap
      default: []
      selector:
        action: {}

    button_2x_up:
      name: Up - Double Tap
      default: []
      selector:
        action: {}

    button_3x_up:
      name: Up - Triple Tap
      default: []
      selector:
        action: {}

    # =============================
    # DOWN BUTTON ACTIONS (001)
    # =============================

    button_1x_down:
      name: Down - Single Tap
      default: []
      selector:
        action: {}

    button_2x_down:
      name: Down - Double Tap
      default: []
      selector:
        action: {}

    button_3x_down:
      name: Down - Triple Tap
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input inovelli_switch

variables:
  scene_id: "{{ trigger.event.data.property_key_name }}"
  scene_value: "{{ trigger.event.data.value | int }}"

action:
  - choose:

      # =============================
      # UP PADDLE (002)
      # =============================

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "002" and scene_value == 0 }}
        sequence: !input button_1x_up

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "002" and scene_value == 3 }}
        sequence: !input button_2x_up

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "002" and scene_value == 4 }}
        sequence: !input button_3x_up


      # =============================
      # DOWN PADDLE (001)
      # =============================

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "001" and scene_value == 0 }}
        sequence: !input button_1x_down

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "001" and scene_value == 3 }}
        sequence: !input button_2x_down

      - conditions:
          - condition: template
            value_template: >
              {{ scene_id == "001" and scene_value == 4 }}
        sequence: !input button_3x_down
